### ISSUE TITLE
FIX: Explore Weighted Random Feature Selection

### ISSUE THREAD

**Issue by shamindras** [Yu-Group/scikit-learn-sandbox#19]
This is the weighted random feature selection using the feature importances from the random forest package:

- [ ] [Code reference](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/tree/_splitter.pyx#L401-L402) for the splitting 
- [ ] Code reference for the [Uniform Random Number](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/tree/_utils.pyx#L72-L75) generator
- [ ] Need to write new versions of these functions (CHECK!) to use weighted feature importances
i.e. assume feature importances are passed through in a numpy array format as an input.
- [ ] Check that the distribution of the sampled values matches the distribution of the numpy array
- [ ] Do some speed benchmark tests against the existing sampling version

**Comment by shifwang** [comment]
Some ideas regarding how to change this:

1, Add a new attribute to python class tree "feature weight" to store weights for each feature.
2, rewrite the rand_int sampling method in utils to incorporate sampling with feature weights.

One thing need to check with Karl: feature weights will affect the probability whether it will be chosen as a split, but will the feature weight also affect the evaluation of a certain split when calculating impurity?

It is good to have the source code for iRF R package.

**Comment by shamindras** [comment]
> 1, Add a new attribute to python class tree "feature weight" to store weight for each feature.
> 2, rewrite the rand_int sampling method in utils to incorporate sampling with feature weights.
> 

@shifwang - great points! This is the approach we are planning to take based on discussions with @stefanv today.

> One thing need to check with Karl: feature weights will affect the probability whether it will be chosen as a split, but will the feature weight also affect the evaluation of a certain split when calculating impurity?

@shifwang - are you able to liaise with Karl on this to confirm the impacts?

> It will be good to have the source code for iRF R package.

It [is here](https://github.com/sumbose/iRF)

**Comment by shamindras** [comment]
@Runjing-Liu120 / @shifwang, a few small notes for the weighted feature sampling:

As @Runjing-Liu120 had suggested previously it is best to use [np.random.choice](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html) for our initial purposes.

We should ensure that we add in more graphical checks that `np.random.choice` is doing what we want i.e. plot histograms of weighted features and compare them to feature importance plots.

**Comment by shifwang** [comment]
@shamindras Bryan and I explored on this issue yesterday and it turns out we are not able to use np.random.choice because the code is written in cython and does not allow us to use np.random.choice directly.

**Comment by shamindras** [comment]
@shifwang - I see. I thought we could use [numpy in cython](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/tree/_splitter.pyx#L37) directly?
We should discuss further today

**Comment by shifwang** [comment]
@shamindras We did see in the cython that there is "import numpy". But when we add np.random.choice the code gave an error. I think the issue is that cython can use numpy but does not allow advanced data types, which has been used in that particular function.

**Comment by stefanv** [comment]
I'm not in front of a pc now to check the code, but you can execute Python 
from within Cython, unless you are within a cdef function.

If the function is cdef, you may have to hook into mtrand directly to 
execute random_int. We have some examples of that, I'm sure.

**Comment by shifwang** [comment]
@stefanv Yes, it is inside the cdef function. In order to do weighted sampling, we need to have a uniform random number between 0 and 1, is there any function in mtrand we can achieve that? Thank you for the help.

**Comment by stefanv** [comment]
Yes, mtrand can give that. You may also be able to use the rng currently 
employed by scikit-learn.

**Comment by stefanv** [comment]
There are also some other trivial one-liner rng implementations which 
aren't perfect, but may be good enough for your purposes.

**Comment by shifwang** [comment]
Thank you all for all the input regarding this issue! Currently the weighted version is running.
