### ISSUE TITLE
FIX: RIT dtree.tree_.feature issue

### ISSUE THREAD

**Issue by shifwang** [Yu-Group/scikit-learn-sandbox#94]
In dtree.tree_.feature, it has -2 which should be disgarded when doing RIT.

**Comment by shifwang** [comment]
@Runjing-Liu120 Where do we need to modify to solve this issue?

**Comment by Runjing-Liu120** [comment]
Ah I can fix this ; I'll send a pull request in a second

**Comment by Runjing-Liu120** [comment]
Ah sorry ... I'm no longer sure how github works anymore/how to change and push the iRF_utils now that it is in sklearn (not the sandbox). I need to ask you about how this works tomorrow... But I can point to where it is, and it should be an easy fix. 

If you go into iRF_utils, and search for the function "get_tree_data" you'll find a line in that function that says 

node_features_raw_idx = dtree.tree_.feature

so from the list "node_features_raw_idx" you'll want to just remove the -2's.

**Comment by shifwang** [comment]
It's all right, let's discuss about this tomorrow... I am not familiar with the RIT part but by removing all the -2's will it cause trouble when you sampling the paths?

**Comment by shifwang** [comment]
Re the workflow, we could either add irf_utils in the scikit-learn feature_weight branch or modify it directly in the Yu-group/scikit-learn-sandbox and copy it into scikit-learn manually. We can fix this tomorrow...

**Comment by Runjing-Liu120** [comment]
Yes, I think you make a good point; we may not actually want to get rid of the -2's because of how we extract paths from the RF. I'll take a closer look, and we can talk more tomorrow

**Comment by shifwang** [comment]
Finally we found this is sth that has been handled in the current version.
